captcha:
    height: 80
    width: 240
    length: 6
    max_skew: 0.7
    dot_count: 80
    expiration: 5
email:
    host: smtp.qq.com
    port: 465
    from: 1664542528@qq.com
    nickname: 博客系统
    secret: rjeutmdoclngfajb
    is_ssl: true
es:
    url: http://127.0.0.1:9200
    username: ""
    password: ""
    is_console_print: true
gaode:
    enable: false
    key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
jwt:
    access_token_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    refresh_token_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    access_token_expiry_time: 120
    refresh_token_expiry_time: 10080
    issuer: go_blog
mysql:
    host: 127.0.0.1
    port: 3306
    config: charset=utf8mb4&parseTime=True&loc=Local
    username: root
    password: root
    db_name: blog_db
    max_idle_conns: 10
    max_open_conns: 100
    max_life_time: 300s
    max_idle_time: 60s
    log_mode: error
qiniu:
    zone: z0
    bucket: xxx
    img_path: https://xxx.xxx/
    access_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    secret_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    use_https: true
    use_cdn_domains: true
qq:
    enable: false
    app_id: "000000000"
    app_key: xxxxxxxxxxxxxxxx
    redirect_uri: http://xxx.xxx/xxx
redis:
    address: 127.0.0.1:6379
    password: ""
    db: 0
    pool_size: 10        
    min_idle_conns: 3     
    idle_timeout: 300s
system:
    host: 0.0.0.0
    port: 8080
    env: release
    router_prefix: api
    use_multipoint: true
    sessions_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    oss_type: local
    read_timeout: 30s
    write_timeout: 30s
    idle_timeout: 30s
    max_header_bytes: 1 << 20
upload:
    size: 20
    path: uploads
website:
    logo: ""
    full_logo: ""
    title: 博客标题-xxx的个人博客
    slogan: 博客标题
    slogan_en: Blog Title
    description: 博客描述
    version: 1.0.0
    created_at: "2025-1-15"
    icp_filing: icp备案号
    public_security_filing: 公安备案号
    bilibili_url: https://space.bilibili.com/xxx
    gitee_url: https://gitee.com/xxx
    github_url: https://github.com/xxx/
    name: 昵称
    job: 工作
    address: 地址
    email: xxx@qq.com
    qq_image: ""
    wechat_image: ""
zap:
    level: info
    filename: log/my_blog.log
    max_size: 5
    max_backups: 5
    max_age: 5
    is_console_print: true